#!/bin/bash
# sandbox-install-macos.sh — Install and manage a sandboxed environment for
# safe-agent on macOS using Seatbelt profiles (sandbox-exec), a dedicated
# service user, and launchd.
#
# Usage:
#   sandbox-install-macos.sh setup   [-b /path/to/safe-agent]
#   sandbox-install-macos.sh start   [-- safe-agent-args...]
#   sandbox-install-macos.sh stop
#   sandbox-install-macos.sh shell
#   sandbox-install-macos.sh status
#   sandbox-install-macos.sh teardown
#
# Environment overrides:
#   SA_ROOT      Sandbox root directory  (default: /usr/local/var/safe-agent)
#   SA_BINARY    Path to safe-agent bin  (default: ./target/release/safe-agent)
#   SA_USER      Runtime user            (default: _safeagent)
#
# Copyright (c) 2026 Pegasus Heavy Industries LLC
# Contact: pegasusheavyindustries@gmail.com

set -euo pipefail

# ── Defaults ─────────────────────────────────────────────────────────

SA_ROOT="${SA_ROOT:-/usr/local/var/safe-agent}"
SA_USER="${SA_USER:-_safeagent}"
SA_BINARY="${SA_BINARY:-./target/release/safe-agent}"
PLIST_LABEL="com.pegasusheavyindustries.safe-agent"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"
SANDBOX_PROFILE="$SA_ROOT/etc/sandbox.sb"
PID_FILE="$SA_ROOT/run/safe-agent.pid"

# ── Logging ──────────────────────────────────────────────────────────

log()  { printf '\033[0;32m[+]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
err()  { printf '\033[0;31m[x]\033[0m %s\n' "$*" >&2; }
info() { printf '\033[0;36m[i]\033[0m %s\n' "$*"; }

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        err "This command must be run as root (use sudo)."
        exit 1
    fi
}

require_macos() {
    if [ "$(uname -s)" != "Darwin" ]; then
        err "This script is for macOS only."
        exit 1
    fi
}

# ── User management ─────────────────────────────────────────────────

user_exists() {
    dscl . -read "/Users/$SA_USER" &>/dev/null
}

create_user() {
    if user_exists; then
        info "User '$SA_USER' already exists."
        return
    fi

    log "Creating service user '$SA_USER'..."

    # Find an unused UID in the service range (400-499)
    local uid=450
    while dscl . -list /Users UniqueID | awk '{print $2}' | grep -q "^${uid}$"; do
        uid=$((uid + 1))
    done

    local gid=$uid

    # Create group
    dscl . -create "/Groups/$SA_USER"
    dscl . -create "/Groups/$SA_USER" PrimaryGroupID "$gid"
    dscl . -create "/Groups/$SA_USER" RealName "safe-agent service"

    # Create user
    dscl . -create "/Users/$SA_USER"
    dscl . -create "/Users/$SA_USER" UniqueID "$uid"
    dscl . -create "/Users/$SA_USER" PrimaryGroupID "$gid"
    dscl . -create "/Users/$SA_USER" UserShell /usr/bin/false
    dscl . -create "/Users/$SA_USER" RealName "safe-agent service account"
    dscl . -create "/Users/$SA_USER" NFSHomeDirectory "$SA_ROOT/home"

    # Hide from login window
    dscl . -create "/Users/$SA_USER" IsHidden 1

    log "Created service user '$SA_USER' (UID $uid)."
}

# ── Directory setup ──────────────────────────────────────────────────

create_dirs() {
    log "Creating sandbox directory tree at $SA_ROOT"

    local dirs=(
        "$SA_ROOT"
        "$SA_ROOT/bin"
        "$SA_ROOT/data/skills"
        "$SA_ROOT/config"
        "$SA_ROOT/home"
        "$SA_ROOT/home/.claude"
        "$SA_ROOT/temp"
        "$SA_ROOT/run"
        "$SA_ROOT/logs"
        "$SA_ROOT/etc"
    )

    for d in "${dirs[@]}"; do
        mkdir -p "$d"
    done

    # Ownership: safeagent owns the whole tree
    chown -R "$SA_USER:$SA_USER" "$SA_ROOT"

    # Permissions: user rwx, group rx, other none
    chmod -R 750 "$SA_ROOT"
    # temp needs to be writable
    chmod 1700 "$SA_ROOT/temp"

    log "Directory tree created and permissions set."
}

# ── Seatbelt sandbox profile ────────────────────────────────────────

generate_sandbox_profile() {
    log "Generating Seatbelt sandbox profile..."

    # Resolve Homebrew prefix (different on Intel vs Apple Silicon)
    local brew_prefix="/usr/local"
    if [ -d "/opt/homebrew" ]; then
        brew_prefix="/opt/homebrew"
    fi

    cat > "$SANDBOX_PROFILE" <<SBEOF
;; Seatbelt sandbox profile for safe-agent
;; Generated by sandbox-install-macos.sh
;; Copyright (c) 2026 Pegasus Heavy Industries LLC

(version 1)

;; Default deny — everything is blocked unless explicitly allowed
(deny default)

;; ── File access ─────────────────────────────────────────────────────

;; Read-write access to the sandbox directory
(allow file-read* file-write*
    (subpath "${SA_ROOT}"))

;; Read-only system libraries and frameworks
(allow file-read*
    (subpath "/usr/lib")
    (subpath "/usr/share")
    (subpath "/System/Library")
    (subpath "/Library/Frameworks")
    (subpath "/private/var/db/dyld")
    (subpath "/dev/null")
    (subpath "/dev/zero")
    (subpath "/dev/random")
    (subpath "/dev/urandom")
    (literal "/dev/tty"))

;; Read-only access to Homebrew (git, build deps, etc.)
(allow file-read*
    (subpath "${brew_prefix}"))

;; Read-only access to nvm/pyenv managed runtimes (inside sandbox root)
(allow file-read*
    (subpath "${SA_ROOT}/nvm")
    (subpath "${SA_ROOT}/pyenv"))

;; Read-only access to system config
(allow file-read*
    (literal "/etc/resolv.conf")
    (literal "/etc/hosts")
    (literal "/etc/localtime")
    (literal "/etc/passwd")
    (literal "/etc/group")
    (literal "/private/etc/resolv.conf")
    (literal "/private/etc/hosts")
    (literal "/private/etc/localtime")
    (literal "/private/etc/passwd")
    (literal "/private/etc/group"))

;; TLS certificates
(allow file-read*
    (subpath "/etc/ssl")
    (subpath "/private/etc/ssl")
    (subpath "${brew_prefix}/etc/openssl")
    (subpath "${brew_prefix}/share/ca-certificates"))

;; Temp directories (needed by Python, Node.js, etc.)
(allow file-read* file-write*
    (subpath "${SA_ROOT}/temp")
    (subpath "/private/var/folders"))

;; Process execution
(allow file-read*
    (literal "/usr/bin/env")
    (literal "/bin/sh")
    (literal "/bin/bash"))

;; Homebrew binaries (git, build deps, etc.)
(allow process-exec
    (subpath "${brew_prefix}/bin")
    (subpath "${brew_prefix}/opt")
    (subpath "${brew_prefix}/lib")
    (subpath "${brew_prefix}/Cellar"))

;; nvm-managed Node.js and pyenv-managed Python
(allow process-exec
    (subpath "${SA_ROOT}/nvm")
    (subpath "${SA_ROOT}/pyenv"))

;; safe-agent binary
(allow process-exec
    (literal "${SA_ROOT}/bin/safe-agent"))

;; System interpreters
(allow process-exec
    (literal "/usr/bin/env")
    (literal "/bin/sh")
    (literal "/bin/bash"))

;; ── Process ─────────────────────────────────────────────────────────

(allow process-fork)

;; Allow spawning child processes (skills, bridges)
(allow process-exec)

;; ── Network ─────────────────────────────────────────────────────────

;; Allow all network access (dashboard, API calls, tunnels)
(allow network*)

;; ── Mach / IPC ──────────────────────────────────────────────────────

;; Allow basic Mach IPC (required for DNS resolution, security framework)
(allow mach-lookup
    (global-name "com.apple.SecurityServer")
    (global-name "com.apple.SystemConfiguration.configd")
    (global-name "com.apple.SystemConfiguration.DNSConfiguration")
    (global-name "com.apple.system.DirectoryService.libinfo_v1")
    (global-name "com.apple.system.logger")
    (global-name "com.apple.cfprefsd.daemon")
    (global-name "com.apple.cfprefsd.agent")
    (global-name "com.apple.distributed_notifications@1v3")
    (global-name "com.apple.lsd.mapdb")
    (global-name "com.apple.coreservices.launchservicesd")
    (global-name "com.apple.trustd.agent")
    (global-name "com.apple.trustd"))

;; ── Sysctl ──────────────────────────────────────────────────────────

(allow sysctl-read)

;; ── Signals ─────────────────────────────────────────────────────────

;; Allow sending signals to own process group
(allow signal (target self))
SBEOF

    chmod 644 "$SANDBOX_PROFILE"
    chown "$SA_USER:$SA_USER" "$SANDBOX_PROFILE"
    log "Sandbox profile written to $SANDBOX_PROFILE"
}

# ── nvm / pyenv ─────────────────────────────────────────────────────

NVM_DIR="${NVM_DIR:-$SA_ROOT/nvm}"
PYENV_ROOT="${PYENV_ROOT:-$SA_ROOT/pyenv}"
NODE_VERSION="--lts"
PYTHON_VERSION="3.12"

load_nvm() {
    export NVM_DIR
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
}

load_pyenv() {
    export PYENV_ROOT
    export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
    command -v pyenv &>/dev/null && eval "$(pyenv init -)"
}

# ── Dependency installation ─────────────────────────────────────────

install_dependencies() {
    # Homebrew is only needed for git and build deps (not Node/Python)
    if ! command -v brew &>/dev/null; then
        err "Homebrew is not installed. Install it first:"
        err '  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
        exit 1
    fi

    # Base tools via Homebrew
    log "Installing base tools via Homebrew..."
    local pkgs=()
    command -v git &>/dev/null || pkgs+=(git)
    # pyenv build deps (openssl, readline, etc.)
    pkgs+=(openssl readline sqlite3 xz zlib)
    brew install "${pkgs[@]}" 2>/dev/null || true

    # nvm + Node.js LTS
    if [ -s "$NVM_DIR/nvm.sh" ]; then
        info "nvm already installed at $NVM_DIR"
    else
        log "Installing nvm..."
        mkdir -p "$NVM_DIR"
        curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | \
            NVM_DIR="$NVM_DIR" bash
    fi
    load_nvm

    if nvm ls "$NODE_VERSION" &>/dev/null; then
        info "Node.js LTS already installed via nvm."
    else
        log "Installing Node.js LTS via nvm..."
        nvm install "$NODE_VERSION"
    fi
    nvm use "$NODE_VERSION"
    nvm alias default "$NODE_VERSION"
    log "Node.js $(node --version) active via nvm."

    # pyenv + Python
    if [ -d "$PYENV_ROOT/bin" ]; then
        info "pyenv already installed at $PYENV_ROOT"
    else
        log "Installing pyenv..."
        curl -fsSL https://pyenv.run | PYENV_ROOT="$PYENV_ROOT" bash
    fi
    load_pyenv

    if pyenv versions --bare | grep -q "^${PYTHON_VERSION}"; then
        info "Python $PYTHON_VERSION already installed via pyenv."
    else
        log "Installing Python $PYTHON_VERSION via pyenv..."
        pyenv install "$PYTHON_VERSION"
    fi
    pyenv global "$PYTHON_VERSION"
    log "Python $(python3 --version) active via pyenv."

    # Claude Code CLI (uses nvm-managed npm)
    if ! command -v claude &>/dev/null; then
        log "Installing Claude Code CLI..."
        npm install -g @anthropic-ai/claude-code
    else
        info "Claude Code CLI already installed."
    fi

    # ngrok
    local ngrok_path="$SA_ROOT/bin/ngrok"
    if [ ! -f "$ngrok_path" ]; then
        log "Installing ngrok..."
        local arch="amd64"
        [ "$(uname -m)" = "arm64" ] && arch="arm64"
        curl -fsSL "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-${arch}.zip" \
            -o /tmp/ngrok.zip
        unzip -o /tmp/ngrok.zip -d "$SA_ROOT/bin" >/dev/null
        rm -f /tmp/ngrok.zip
        chmod +x "$ngrok_path"
    else
        info "ngrok already installed."
    fi

    # Python packages for skills (uses pyenv-managed pip)
    log "Installing Python packages for skills..."
    pip install --quiet \
        requests \
        google-api-python-client \
        google-auth-httplib2 \
        google-auth-oauthlib \
        python-dotenv \
        schedule \
        httpx \
        beautifulsoup4 \
        feedparser \
        icalendar
}

# ── Binary installation ─────────────────────────────────────────────

install_binary() {
    local binary="$1"

    if [ ! -f "$binary" ]; then
        err "safe-agent binary not found at: $binary"
        err "Build it first (cargo build --release) or set SA_BINARY."
        exit 1
    fi

    install -m 0755 "$binary" "$SA_ROOT/bin/safe-agent"
    log "Installed safe-agent binary to $SA_ROOT/bin/"
}

# ── launchd plist ────────────────────────────────────────────────────

install_launchd_plist() {
    log "Installing launchd plist: $PLIST_LABEL"

    # Resolve Homebrew prefix and nvm/pyenv paths
    local brew_prefix="/usr/local"
    [ -d "/opt/homebrew" ] && brew_prefix="/opt/homebrew"

    local nvm_bin=""
    if [ -d "$SA_ROOT/nvm/versions/node" ]; then
        local nvm_node_ver
        nvm_node_ver="$(ls "$SA_ROOT/nvm/versions/node/" 2>/dev/null | tail -1)"
        [ -n "$nvm_node_ver" ] && nvm_bin="$SA_ROOT/nvm/versions/node/$nvm_node_ver/bin"
    fi
    local pyenv_bin="$SA_ROOT/pyenv/shims:$SA_ROOT/pyenv/bin"
    local full_path="${nvm_bin:+$nvm_bin:}${pyenv_bin}:${SA_ROOT}/bin:${brew_prefix}/bin:${brew_prefix}/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

    local plist_dir
    plist_dir="$(dirname "$PLIST_PATH")"
    mkdir -p "$plist_dir"

    cat > "$PLIST_PATH" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/sandbox-exec</string>
        <string>-f</string>
        <string>${SANDBOX_PROFILE}</string>
        <string>${SA_ROOT}/bin/safe-agent</string>
    </array>

    <key>UserName</key>
    <string>${SA_USER}</string>

    <key>GroupName</key>
    <string>${SA_USER}</string>

    <key>WorkingDirectory</key>
    <string>${SA_ROOT}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>XDG_DATA_HOME</key>
        <string>${SA_ROOT}/data</string>
        <key>XDG_CONFIG_HOME</key>
        <string>${SA_ROOT}/config</string>
        <key>HOME</key>
        <string>${SA_ROOT}/home</string>
        <key>TEMP</key>
        <string>${SA_ROOT}/temp</string>
        <key>TMPDIR</key>
        <string>${SA_ROOT}/temp</string>
        <key>NVM_DIR</key>
        <string>${SA_ROOT}/nvm</string>
        <key>PYENV_ROOT</key>
        <string>${SA_ROOT}/pyenv</string>
        <key>PATH</key>
        <string>${full_path}</string>
    </dict>

    <key>RunAtLoad</key>
    <false/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>StandardOutPath</key>
    <string>${SA_ROOT}/logs/stdout.log</string>

    <key>StandardErrorPath</key>
    <string>${SA_ROOT}/logs/stderr.log</string>

    <key>SoftResourceLimits</key>
    <dict>
        <key>NumberOfProcesses</key>
        <integer>128</integer>
        <key>NumberOfFiles</key>
        <integer>4096</integer>
    </dict>

    <key>HardResourceLimits</key>
    <dict>
        <key>NumberOfProcesses</key>
        <integer>256</integer>
        <key>NumberOfFiles</key>
        <integer>8192</integer>
    </dict>
</dict>
</plist>
PLISTEOF

    log "launchd plist written to $PLIST_PATH"
    info "Load with:    launchctl load $PLIST_PATH"
    info "Start with:   launchctl start $PLIST_LABEL"
    info "Stop with:    launchctl stop $PLIST_LABEL"
    info "Logs in:      $SA_ROOT/logs/"
}

# ── Environment file ────────────────────────────────────────────────

write_env_hint() {
    local env_path="$SA_ROOT/config/sandbox.env"
    if [ -f "$env_path" ]; then
        info "Environment file already exists at $env_path"
        return
    fi

    cat > "$env_path" <<'ENVEOF'
# safe-agent sandbox environment variables
# Edit this file, then restart the agent.
# Note: for launchd, env vars are set in the plist. This file is used
# by the manual 'start' command.

# Required: set these before starting
# DASHBOARD_PASSWORD=changeme
# JWT_SECRET=changeme
# TELEGRAM_BOT_TOKEN=

# Optional
# TUNNEL_URL=
# NGROK_AUTHTOKEN=
ENVEOF

    chown "$SA_USER:$SA_USER" "$env_path"
    chmod 640 "$env_path"
    log "Environment template written to $env_path"
}

read_env_file() {
    local env_path="$SA_ROOT/config/sandbox.env"
    if [ -f "$env_path" ]; then
        while IFS='=' read -r key value; do
            key="$(echo "$key" | xargs)"
            if [ -n "$key" ] && [ "${key:0:1}" != "#" ]; then
                export "$key=$value"
            fi
        done < "$env_path"
    fi
}

# ── Commands ─────────────────────────────────────────────────────────

cmd_setup() {
    require_macos
    require_root

    local binary="$SA_BINARY"
    while [ $# -gt 0 ]; do
        case "$1" in
            -b|--binary) binary="$2"; shift 2 ;;
            *) err "Unknown option: $1"; exit 1 ;;
        esac
    done

    install_dependencies
    create_user
    create_dirs
    install_binary "$binary"
    generate_sandbox_profile
    write_env_hint
    install_launchd_plist

    # Fix ownership after all files are in place
    chown -R "$SA_USER:$SA_USER" "$SA_ROOT"

    echo ""
    log "Setup complete!"
    echo ""
    info "Sandbox root:  $SA_ROOT"
    info "Runtime user:  $SA_USER"
    info "Data dir:      $SA_ROOT/data/"
    info "Config dir:    $SA_ROOT/config/"
    info "Sandbox profile: $SANDBOX_PROFILE"
    info "launchd plist: $PLIST_PATH"
    echo ""
    info "Next steps:"
    info "  1. Copy config.toml to: $SA_ROOT/config/"
    info "  2. Edit the launchd plist to add env vars:"
    info "     $PLIST_PATH"
    info "     (DASHBOARD_PASSWORD, JWT_SECRET, etc.)"
    info "  3. Start: sudo $0 start"
    info "     Or:    launchctl load $PLIST_PATH && launchctl start $PLIST_LABEL"
}

cmd_start() {
    require_macos
    require_root

    local exe="$SA_ROOT/bin/safe-agent"
    if [ ! -f "$exe" ]; then
        err "safe-agent not found in sandbox. Run setup first."
        exit 1
    fi

    # Check if already running
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        err "safe-agent is already running (PID $(cat "$PID_FILE"))."
        exit 1
    fi

    # Load environment
    export XDG_DATA_HOME="$SA_ROOT/data"
    export XDG_CONFIG_HOME="$SA_ROOT/config"
    export HOME="$SA_ROOT/home"
    export TMPDIR="$SA_ROOT/temp"
    read_env_file

    # Resolve Homebrew prefix and nvm/pyenv paths
    local brew_prefix="/usr/local"
    [ -d "/opt/homebrew" ] && brew_prefix="/opt/homebrew"

    # nvm node binary directory
    local nvm_bin=""
    if [ -d "$SA_ROOT/nvm/versions/node" ]; then
        local nvm_node_ver
        nvm_node_ver="$(ls "$SA_ROOT/nvm/versions/node/" 2>/dev/null | tail -1)"
        [ -n "$nvm_node_ver" ] && nvm_bin="$SA_ROOT/nvm/versions/node/$nvm_node_ver/bin"
    fi
    local pyenv_bin="$SA_ROOT/pyenv/shims:$SA_ROOT/pyenv/bin"

    export NVM_DIR="$SA_ROOT/nvm"
    export PYENV_ROOT="$SA_ROOT/pyenv"
    export PATH="${nvm_bin:+$nvm_bin:}${pyenv_bin}:$SA_ROOT/bin:$brew_prefix/bin:$brew_prefix/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

    log "Starting safe-agent as $SA_USER with Seatbelt sandbox..."

    # Run under sandbox-exec as the service user
    sudo -u "$SA_USER" \
        XDG_DATA_HOME="$XDG_DATA_HOME" \
        XDG_CONFIG_HOME="$XDG_CONFIG_HOME" \
        HOME="$HOME" \
        TMPDIR="$TMPDIR" \
        NVM_DIR="$NVM_DIR" \
        PYENV_ROOT="$PYENV_ROOT" \
        PATH="$PATH" \
        sandbox-exec -f "$SANDBOX_PROFILE" \
        "$exe" "$@" &

    local pid=$!
    echo "$pid" > "$PID_FILE"
    chown "$SA_USER:$SA_USER" "$PID_FILE"

    log "safe-agent started (PID $pid)."
    info "Dashboard: http://localhost:3031"
    info "Logs:      $SA_ROOT/logs/"
    info "Stop:      sudo $0 stop"

    # Wait
    wait "$pid" 2>/dev/null || true
    rm -f "$PID_FILE"
    log "safe-agent exited."
}

cmd_stop() {
    require_macos
    require_root

    # Try launchd first
    launchctl stop "$PLIST_LABEL" 2>/dev/null || true

    # PID file
    if [ -f "$PID_FILE" ]; then
        local pid
        pid="$(cat "$PID_FILE")"
        if kill -0 "$pid" 2>/dev/null; then
            log "Stopping safe-agent (PID $pid)..."
            kill "$pid"
            local i=0
            while kill -0 "$pid" 2>/dev/null && [ $i -lt 15 ]; do
                sleep 1
                i=$((i + 1))
            done
            if kill -0 "$pid" 2>/dev/null; then
                warn "Force-killing PID $pid"
                kill -9 "$pid" 2>/dev/null || true
            fi
        fi
        rm -f "$PID_FILE"
    fi

    # Sweep for any remaining processes
    pkill -u "$SA_USER" -f safe-agent 2>/dev/null || true

    log "Stopped."
}

cmd_shell() {
    require_macos
    require_root

    local brew_prefix="/usr/local"
    [ -d "/opt/homebrew" ] && brew_prefix="/opt/homebrew"

    # nvm/pyenv paths
    local nvm_bin=""
    if [ -d "$SA_ROOT/nvm/versions/node" ]; then
        local nvm_node_ver
        nvm_node_ver="$(ls "$SA_ROOT/nvm/versions/node/" 2>/dev/null | tail -1)"
        [ -n "$nvm_node_ver" ] && nvm_bin="$SA_ROOT/nvm/versions/node/$nvm_node_ver/bin"
    fi
    local pyenv_bin="$SA_ROOT/pyenv/shims:$SA_ROOT/pyenv/bin"

    info "Opening shell as $SA_USER with Seatbelt sandbox..."
    info "Type 'exit' to leave."

    sudo -u "$SA_USER" \
        XDG_DATA_HOME="$SA_ROOT/data" \
        XDG_CONFIG_HOME="$SA_ROOT/config" \
        HOME="$SA_ROOT/home" \
        TMPDIR="$SA_ROOT/temp" \
        NVM_DIR="$SA_ROOT/nvm" \
        PYENV_ROOT="$SA_ROOT/pyenv" \
        PATH="${nvm_bin:+$nvm_bin:}${pyenv_bin}:$SA_ROOT/bin:$brew_prefix/bin:$brew_prefix/sbin:/usr/bin:/bin:/usr/sbin:/sbin" \
        TERM="${TERM:-xterm-256color}" \
        sandbox-exec -f "$SANDBOX_PROFILE" \
        /bin/bash -l || true

    info "Shell session ended."
}

cmd_status() {
    require_macos

    printf '\033[0;36m── safe-agent sandbox status (macOS) ──\033[0m\n\n'

    # Sandbox dir
    if [ ! -d "$SA_ROOT" ]; then
        warn "Sandbox does not exist: $SA_ROOT"
        warn "Run '$0 setup' first."
        return
    fi
    info "Sandbox root: $SA_ROOT"

    # User
    echo ""
    printf '\033[0;36mUser:\033[0m\n'
    if user_exists; then
        local uid
        uid="$(dscl . -read "/Users/$SA_USER" UniqueID 2>/dev/null | awk '{print $2}')"
        printf '  \033[0;32m●\033[0m %s (UID %s)\n' "$SA_USER" "$uid"
    else
        printf '  \033[0;31m○\033[0m %s does not exist\n' "$SA_USER"
    fi

    # Sandbox profile
    echo ""
    printf '\033[0;36mSandbox profile:\033[0m\n'
    if [ -f "$SANDBOX_PROFILE" ]; then
        printf '  \033[0;32m●\033[0m %s\n' "$SANDBOX_PROFILE"
    else
        printf '  \033[0;31m○\033[0m not found\n'
    fi

    # Process
    echo ""
    printf '\033[0;36mProcess:\033[0m\n'
    if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        local pid
        pid="$(cat "$PID_FILE")"
        printf '  \033[0;32m●\033[0m safe-agent running (PID %s)\n' "$pid"
    elif pgrep -u "$SA_USER" -f safe-agent &>/dev/null; then
        local pid
        pid="$(pgrep -u "$SA_USER" -f safe-agent | head -1)"
        printf '  \033[0;32m●\033[0m safe-agent running (PID %s)\n' "$pid"
    else
        printf '  \033[0;31m○\033[0m safe-agent not running\n'
    fi

    # launchd
    echo ""
    printf '\033[0;36mlaunchd:\033[0m\n'
    if [ -f "$PLIST_PATH" ]; then
        local loaded
        loaded="$(launchctl list 2>/dev/null | grep "$PLIST_LABEL" || true)"
        if [ -n "$loaded" ]; then
            printf '  \033[0;32m●\033[0m %s (loaded)\n' "$PLIST_LABEL"
        else
            printf '  \033[1;33m○\033[0m %s (not loaded)\n' "$PLIST_LABEL"
        fi
    else
        printf '  \033[0;31m○\033[0m plist not installed\n'
    fi

    # Disk
    echo ""
    printf '\033[0;36mDisk usage:\033[0m\n'
    for name in data config home logs; do
        local dir="$SA_ROOT/$name"
        if [ -d "$dir" ]; then
            local size
            size="$(du -sh "$dir" 2>/dev/null | cut -f1)"
            printf '  %-8s %s (%s)\n' "$name:" "$dir" "$size"
        fi
    done

    echo ""
}

cmd_teardown() {
    require_macos
    require_root

    warn "This will REMOVE the sandbox at $SA_ROOT,"
    warn "unload the launchd plist, and remove the sandbox profile."
    printf 'Are you sure? [y/N] '
    read -r confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        info "Cancelled."
        exit 0
    fi

    # Stop
    cmd_stop 2>/dev/null || true

    # Unload launchd
    if [ -f "$PLIST_PATH" ]; then
        launchctl unload "$PLIST_PATH" 2>/dev/null || true
        rm -f "$PLIST_PATH"
        log "Removed launchd plist."
    fi

    # Remove sandbox directory
    if [ -d "$SA_ROOT" ]; then
        rm -rf "$SA_ROOT"
        log "Removed $SA_ROOT"
    fi

    log "Teardown complete."
    info "The '$SA_USER' user was NOT removed."
    info "Remove manually with: sudo dscl . -delete /Users/$SA_USER && sudo dscl . -delete /Groups/$SA_USER"
}

# ── Main ─────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
safe-agent macOS sandbox installer

Usage: $(basename "$0") <command> [options]

Commands:
  setup    [-b binary]   Install dependencies, create user, build sandbox, install launchd plist
  start    [-- args...]  Start safe-agent in Seatbelt sandbox as service user
  stop                   Stop safe-agent
  shell                  Open a bash shell inside the sandbox
  status                 Show sandbox, process, and launchd status
  teardown               Remove the sandbox, plist, and profile entirely

Options:
  -b, --binary PATH      Path to the safe-agent binary (default: ./target/release/safe-agent)

Environment:
  SA_ROOT     Sandbox root directory  (default: /usr/local/var/safe-agent)
  SA_BINARY   Binary path             (default: ./target/release/safe-agent)
  SA_USER     Runtime user            (default: _safeagent)

Examples:
  sudo ./scripts/sandbox-install-macos.sh setup
  sudo ./scripts/sandbox-install-macos.sh setup -b /usr/local/bin/safe-agent
  sudo ./scripts/sandbox-install-macos.sh start
  sudo ./scripts/sandbox-install-macos.sh shell
  ./scripts/sandbox-install-macos.sh status
  sudo ./scripts/sandbox-install-macos.sh stop
  sudo ./scripts/sandbox-install-macos.sh teardown
EOF
}

case "${1:-}" in
    setup)    shift; cmd_setup "$@" ;;
    start)    shift; cmd_start "$@" ;;
    stop)     cmd_stop ;;
    shell)    cmd_shell ;;
    status)   cmd_status ;;
    teardown) cmd_teardown ;;
    -h|--help|help) usage ;;
    "")       usage; exit 1 ;;
    *)        err "Unknown command: $1"; usage; exit 1 ;;
esac
